### ISSUE TITLE
What happens if Node-Red is restarted 

### ISSUE THREAD

**Issue by marioishikawa** [SenseTecnic/node-red-contrib-mqttdb#1]
Hello, I'd like to know what happens if there is a new deploy or node-red is restarted, regarding NeDB. Is the information at RAM lost? The question came actually on a forked project: node-red-contrib-google-iot-core

**Comment by mblackstock** [comment]
When this node is configured to persist messages, messages are saved in the
database until they are sent and acked, so they are not lost between
redeploy and restarts.

As for the behaviour of NeDB see
https://github.com/louischatriot/nedb/blob/master/README.md for more info.
