### ISSUE TITLE
Persistent outgoing fail.

### ISSUE THREAD

**Issue by agenteDserrano** [SenseTecnic/node-red-contrib-mqttdb#2]
I start this report saying that I think the idea of pesistir mqtt in NEdb seems fabulous.

I installed the node in my local environment and did some tests.
I am connected to my mqtt server and I publish messages without problem.

Then I stop the mqtt server and it is disconnected. Then I publish messages again and I hope to see them in the directory ~ /.node-red/mqttdb/cee0cab4.044ae8
But the files are empty.
-rw-r - r-- 1 dsb dsb **0** Feb 8 16:58 incoming
-rw-r - r-- 1 dsb dsb **0** Feb 8 16:58 outgoing

After start mqtt server again I get no messages.

Thanks for the help in advance.

**Comment by agenteDserrano** [comment]
Hello.. Any help ?

**Comment by mblackstock** [comment]
sorry to take so long with this.  Please try the new release (0.1.2) if you have a chance.

**Comment by Hamster3322** [comment]
Hi, I use also the mqttdb and get a failure in the logs:
![mqttdb_pfad](https://user-images.githubusercontent.com/34606287/107854631-6efb4500-6e1d-11eb-8858-24b746298a34.JPG)
Have anyone an idea? br
